export {
  CONTAINER_KINDS,
  type ContainerKind,
  EDGE_DIRECTIONS,
  EDGE_MODES,
  type EdgeDirection,
  type EdgeMode,
  IR_JSON_SCHEMA,
  IR_KINDS,
  type IrContainer,
  irContainerSchema,
  type IrDocument,
  irDocumentSchema,
  type IrEdge,
  irEdgeSchema,
  type IrKind,
  type IrNode,
  irNodeSchema,
  IrValidationError,
  type IrValidationIssue,
  validateIr,
} from './schema.js';
